#!/bin/bash

set -e
export CC=gcc

if [ -z "$TRAVIS" ]; then
  echo "==> Installing required libraries…"

  if [ "$(uname)" == "Darwin" ]; then
    brew install glib
    brew install gdk-pixbuf
    brew install cairo
    brew install pango
  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    sudo apt-get -qq -y install libxml2-dev libcairo2-dev libpango1.0-dev
  fi
fi

echo "==> Installing gem dependencies…"
bundle check --path vendor/gems 2>&1 > /dev/null || {
  bundle install --binstubs bin --path vendor/gems --quiet
}