#!/bin/bash

set -e
export CC=gcc

echo "==> Initing Git submodules"

git submodule update --init --recursive

echo "==> Installing gem dependencies…"

bundle install --local --binstubs --path vendor/cache "$@"

echo "==> Installing required libraries…"

if [ "$(uname)" == "Darwin" ]; then
  brew install glib gdk-pixbuf cairo pango
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  sudo apt-get -qq -y install libxml2-dev libcairo2-dev libpango1.0-dev ttf-lyx
fi
