#!/usr/bin/ruby
# frozen_string_literal: true

lib = File.expand_path("../../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require "mathematical"

svg = Mathematical.new.render('$f(x) = \int_{-\infty}^\infty\hat f(\xi)\,e^{2 \pi i \xi x}\,d\xi$')[:data]

text = """
<html>

<body>

#{svg}

</body>

</html>
"""

File.open("test.html", "w") { |file| file.write(text) }

unless ARGV[0] == "-s"
  %x(open text.html)
end
