#!/usr/bin/ruby

lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'mathematical'

`bundle exec rake compile`

svg = Mathematical::Render.new.render('$f(x) = \int_{-\infty}^\infty\hat f(\xi)\,e^{2 \pi i \xi x}\,d\xi$')['svg']

text = """
<html>

<body>

#{svg}

</body>


</html>
"""

File.open("text.html", 'w') { |file| file.write(text) }

unless ARGV[0] == "-s"
  `open text.html`
end
